### ISSUE TITLE
add new staff

### ISSUE THREAD

**Issue by C-o-m-o-n** [C-o-m-o-n/textbin#1]

**Comment by r0ld3x** [comment]
add hacktoberfest label

**Comment by r0ld3x** [comment]
done:) now marge it

**Comment by C-o-m-o-n** [comment]
Hey, I was working on the documentation, can you add your part on the documentation?

**Comment by r0ld3x** [comment]
> Hey, I was working on the documentation, can you add your part on the documentation?

sure

**Comment by C-o-m-o-n** [comment]
thanks

**Comment by r0ld3x** [comment]
> thanks

you started ?

**Comment by C-o-m-o-n** [comment]
yah, I was thinking of a github page https://c-o-m-o-n.github.io/textbin/
